#!/bin/bash
[ ! -d /root/blackip ] && mkdir /root/blackip
[ ! -f /lib/ufw/blackip-ipv4.txt ] && touch /lib/ufw/blackip-ipv4.txt
[ ! -f /lib/ufw/blackip-ipv6.txt ] && touch /lib/ufw/blackip-ipv6.txt
[ ! -f /lib/ufw/blackip-ipv4-upded.txt ] && touch /lib/ufw/blackip-ipv4-upded.txt
[ ! -f /lib/ufw/blackip-ipv6-upded.txt ] && touch /lib/ufw/blackip-ipv6-upded.txt

ipset -exist create blackip-ipv4 hash:net family inet
ipset -exist create blackip-ipv6 hash:net family inet6

cd /root/blackip

wget -qO blackip1.txt http://blackip.ustc.edu.cn/list.php?txt && \
wget -qO blackip2.txt http://blackip.ustc.edu.cn/mailblackip.php?txt && \
wget -qO blackip3.txt http://blackip.ustc.edu.cn/dnsblackip.php?txt

[ ! $? -eq 0 ] && exit 0

cat blackip[1-3].txt > blackip.txt

[ `wc -l blackip.txt |awk '{print $1}'` -le 100 ] && exit 0

grep -v ':' blackip.txt |sed 's/^/add blackip-ipv4 /' > blackip-ipv4-new.txt
grep  ':' blackip.txt |sed 's/^/add blackip-ipv6 /' > blackip-ipv6-new.txt

diff -u /lib/ufw/blackip-ipv4.txt blackip-ipv4-new.txt|grep '^-add'|cut -c2-|sed 's/add/del/' > blackip-ipv4-upd.txt
diff -u /lib/ufw/blackip-ipv4.txt blackip-ipv4-new.txt|grep '^+add'|cut -c2- >> blackip-ipv4-upd.txt

diff -u /lib/ufw/blackip-ipv6.txt blackip-ipv6-new.txt|grep '^-add'|cut -c2-|sed 's/add/del/' > blackip-ipv6-upd.txt
diff -u /lib/ufw/blackip-ipv6.txt blackip-ipv6-new.txt|grep '^+add'|cut -c2- >> blackip-ipv6-upd.txt

ipset -R -exist < blackip-ipv4-upd.txt
ipset -R -exist < blackip-ipv6-upd.txt

mv -f blackip-ipv4-new.txt /lib/ufw/blackip-ipv4.txt
mv -f blackip-ipv6-new.txt /lib/ufw/blackip-ipv6.txt
mv -f blackip-ipv4-upd.txt /lib/ufw/blackip-ipv4-upded.txt
mv -f blackip-ipv6-upd.txt /lib/ufw/blackip-ipv6-upded.txt
rm -f blackip*.txt


